### ISSUE TITLE
Compatibility with OneStepCheckout

### ISSUE THREAD

**Issue by sprankhub** [lyra/plugin-magento#18] opened 2020-03-05 13:21 UTC
We use Magento 2.3.4, Onestepcheckout_Iosc 1.2.036 (https://www.onestepcheckout.com/) and Lyranetwork_Lyra 2.4.4.

It seems that the module is not really compatible with OneStepCheckout. I would like that the customer can enter his credit card data directly at the merchant's page and **not** on the Lyra payment page. However, if I configure that in the module, no input fields are shown in the checkout at all. Could you help with that?

**Comment by nabil509** [comment] 2021-03-05 09:42
Hi,

Sorry for the delay. 

We cannot provide support for this issue. The plugin is tested over the standard Magento checkout. There is many One step checkout plugins that are different and most of them do not follow the Magento layout configuration.

The files you should modify to do it yourself are: 
- view/frontend/web/js/view/payment/method-renderer/lyra-standard.js: It contains the JS library management.
- view/frontend/web/template/payment/rest.html: It contains the template that renders embedded fields (only if you want customize rendering).
- You should add the right layout configuration XML file to view/frontend/layout/ directory. This part will be very dependant to the OneStepCheckout plugin you use.

I close this issue since it is not a bug.

**Closed as completed by nabil509** 2021-03-05 09:42 UTC

**Comment by angelflo** [comment] 2021-09-25 13:18
Did you find a solution because, we've got error with this plugin and one step checkout also (amasty one step checkout) ... for info we currently work with another payment extension from Ingenico / Ogone competitor and their extension work perfectly out of the box ... so if not possible to find a fix, we'll cancel our subscription to lyra network and ask a refund because honestly can't loose again a lot of time to fix problem like this in our side
